
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.compiapp.logic;

import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\104\000\002\002\004\000\002\002\003\000\002\002" +
    "\005\000\002\003\005\000\002\004\004\000\002\004\003" +
    "\000\002\004\004\000\002\004\004\000\002\005\006\000" +
    "\002\005\005\000\002\005\004\000\002\005\004\000\002" +
    "\005\004\000\002\005\011\000\002\005\011\000\002\006" +
    "\005\000\002\006\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\004\000\002\006\005\000\002" +
    "\007\005\000\002\007\005\000\002\007\003\000\002\010" +
    "\005\000\002\010\005\000\002\010\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\011\005\000" +
    "\002\012\003\000\002\013\004\000\002\013\003\000\002" +
    "\013\004\000\002\014\005\000\002\014\007\000\002\014" +
    "\007\000\002\014\007\000\002\014\007\000\002\014\007" +
    "\000\002\014\007\000\002\014\007\000\002\014\007\000" +
    "\002\014\007\000\002\014\007\000\002\014\007\000\002" +
    "\014\007\000\002\014\007\000\002\014\007\000\002\014" +
    "\007\000\002\015\003\000\002\015\003\000\002\016\007" +
    "\000\002\017\003\000\002\017\003\000\002\017\003\000" +
    "\002\017\003\000\002\017\003\000\002\017\003\000\002" +
    "\020\003\000\002\020\003\000\002\020\003\000\002\020" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\262\000\004\005\005\001\002\000\004\002\264\001" +
    "\002\000\020\003\200\004\176\007\203\011\201\013\175" +
    "\014\177\074\204\001\002\000\006\002\000\017\007\001" +
    "\002\000\042\023\030\024\023\025\027\026\020\027\012" +
    "\030\010\031\026\032\017\033\025\034\024\035\015\036" +
    "\011\037\016\040\032\041\013\042\022\001\002\000\004" +
    "\021\170\001\002\000\004\021\164\001\002\000\004\021" +
    "\160\001\002\000\004\021\154\001\002\000\046\002\uffde" +
    "\003\152\023\030\024\023\025\027\026\020\027\012\030" +
    "\010\031\026\032\017\033\025\034\024\035\015\036\011" +
    "\037\016\040\032\041\013\042\022\001\002\000\004\021" +
    "\146\001\002\000\004\021\142\001\002\000\004\021\136" +
    "\001\002\000\004\021\132\001\002\000\004\002\uffff\001" +
    "\002\000\004\021\126\001\002\000\004\021\122\001\002" +
    "\000\004\021\112\001\002\000\004\021\106\001\002\000" +
    "\004\021\102\001\002\000\004\021\067\001\002\000\004" +
    "\021\065\001\002\000\046\002\uffdc\003\uffdc\023\uffdc\024" +
    "\uffdc\025\uffdc\026\uffdc\027\uffdc\030\uffdc\031\uffdc\032\uffdc" +
    "\033\uffdc\034\uffdc\035\uffdc\036\uffdc\037\uffdc\040\uffdc\041" +
    "\uffdc\042\uffdc\001\002\000\004\021\033\001\002\000\016" +
    "\043\041\044\040\045\037\046\034\047\042\050\036\001" +
    "\002\000\004\020\uffc4\001\002\000\004\020\043\001\002" +
    "\000\004\020\uffc2\001\002\000\004\020\uffc5\001\002\000" +
    "\004\020\uffc6\001\002\000\004\020\uffc7\001\002\000\004" +
    "\020\uffc3\001\002\000\012\055\046\074\045\077\052\100" +
    "\047\001\002\000\126\002\uffe3\003\uffe3\004\uffe3\006\uffe3" +
    "\007\uffe3\011\uffe3\013\uffe3\014\uffe3\015\uffe3\016\uffe3\020" +
    "\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3" +
    "\030\uffe3\031\uffe3\032\uffe3\033\uffe3\034\uffe3\035\uffe3\036" +
    "\uffe3\037\uffe3\040\uffe3\041\uffe3\042\uffe3\056\uffe3\057\uffe3" +
    "\060\uffe3\061\uffe3\062\uffe3\063\uffe3\064\uffe3\065\uffe3\066" +
    "\uffe3\067\uffe3\070\uffe3\071\uffe3\072\uffe3\074\uffe3\001\002" +
    "\000\126\002\uffe0\003\uffe0\004\uffe0\006\uffe0\007\uffe0\011" +
    "\uffe0\013\uffe0\014\uffe0\015\uffe0\016\uffe0\020\uffe0\022\uffe0" +
    "\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030\uffe0\031" +
    "\uffe0\032\uffe0\033\uffe0\034\uffe0\035\uffe0\036\uffe0\037\uffe0" +
    "\040\uffe0\041\uffe0\042\uffe0\056\uffe0\057\uffe0\060\uffe0\061" +
    "\uffe0\062\uffe0\063\uffe0\064\uffe0\065\uffe0\066\uffe0\067\uffe0" +
    "\070\uffe0\071\uffe0\072\uffe0\074\uffe0\001\002\000\012\055" +
    "\046\074\045\077\052\100\047\001\002\000\126\002\uffe1" +
    "\003\uffe1\004\uffe1\006\uffe1\007\uffe1\011\uffe1\013\uffe1\014" +
    "\uffe1\015\uffe1\016\uffe1\020\uffe1\022\uffe1\023\uffe1\024\uffe1" +
    "\025\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1\032\uffe1\033" +
    "\uffe1\034\uffe1\035\uffe1\036\uffe1\037\uffe1\040\uffe1\041\uffe1" +
    "\042\uffe1\056\uffe1\057\uffe1\060\uffe1\061\uffe1\062\uffe1\063" +
    "\uffe1\064\uffe1\065\uffe1\066\uffe1\067\uffe1\070\uffe1\071\uffe1" +
    "\072\uffe1\074\uffe1\001\002\000\052\002\uffcd\003\uffcd\023" +
    "\uffcd\024\uffcd\025\uffcd\026\uffcd\027\uffcd\030\uffcd\031\uffcd" +
    "\032\uffcd\033\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\040" +
    "\uffcd\041\uffcd\042\uffcd\057\060\060\057\001\002\000\126" +
    "\002\uffe6\003\uffe6\004\uffe6\006\uffe6\007\uffe6\011\uffe6\013" +
    "\uffe6\014\uffe6\015\uffe6\016\uffe6\020\uffe6\022\uffe6\023\uffe6" +
    "\024\uffe6\025\uffe6\026\uffe6\027\uffe6\030\uffe6\031\uffe6\032" +
    "\uffe6\033\uffe6\034\uffe6\035\uffe6\036\uffe6\037\uffe6\040\uffe6" +
    "\041\uffe6\042\uffe6\056\uffe6\057\uffe6\060\uffe6\061\053\062" +
    "\054\063\uffe6\064\uffe6\065\uffe6\066\uffe6\067\uffe6\070\uffe6" +
    "\071\uffe6\072\uffe6\074\uffe6\001\002\000\126\002\uffe2\003" +
    "\uffe2\004\uffe2\006\uffe2\007\uffe2\011\uffe2\013\uffe2\014\uffe2" +
    "\015\uffe2\016\uffe2\020\uffe2\022\uffe2\023\uffe2\024\uffe2\025" +
    "\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\032\uffe2\033\uffe2" +
    "\034\uffe2\035\uffe2\036\uffe2\037\uffe2\040\uffe2\041\uffe2\042" +
    "\uffe2\056\uffe2\057\uffe2\060\uffe2\061\uffe2\062\uffe2\063\uffe2" +
    "\064\uffe2\065\uffe2\066\uffe2\067\uffe2\070\uffe2\071\uffe2\072" +
    "\uffe2\074\uffe2\001\002\000\012\055\046\074\045\077\052" +
    "\100\047\001\002\000\012\055\046\074\045\077\052\100" +
    "\047\001\002\000\126\002\uffe4\003\uffe4\004\uffe4\006\uffe4" +
    "\007\uffe4\011\uffe4\013\uffe4\014\uffe4\015\uffe4\016\uffe4\020" +
    "\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4" +
    "\030\uffe4\031\uffe4\032\uffe4\033\uffe4\034\uffe4\035\uffe4\036" +
    "\uffe4\037\uffe4\040\uffe4\041\uffe4\042\uffe4\056\uffe4\057\uffe4" +
    "\060\uffe4\061\uffe4\062\uffe4\063\uffe4\064\uffe4\065\uffe4\066" +
    "\uffe4\067\uffe4\070\uffe4\071\uffe4\072\uffe4\074\uffe4\001\002" +
    "\000\126\002\uffe5\003\uffe5\004\uffe5\006\uffe5\007\uffe5\011" +
    "\uffe5\013\uffe5\014\uffe5\015\uffe5\016\uffe5\020\uffe5\022\uffe5" +
    "\023\uffe5\024\uffe5\025\uffe5\026\uffe5\027\uffe5\030\uffe5\031" +
    "\uffe5\032\uffe5\033\uffe5\034\uffe5\035\uffe5\036\uffe5\037\uffe5" +
    "\040\uffe5\041\uffe5\042\uffe5\056\uffe5\057\uffe5\060\uffe5\061" +
    "\uffe5\062\uffe5\063\uffe5\064\uffe5\065\uffe5\066\uffe5\067\uffe5" +
    "\070\uffe5\071\uffe5\072\uffe5\074\uffe5\001\002\000\012\055" +
    "\046\074\045\077\052\100\047\001\002\000\012\055\046" +
    "\074\045\077\052\100\047\001\002\000\126\002\uffe8\003" +
    "\uffe8\004\uffe8\006\uffe8\007\uffe8\011\uffe8\013\uffe8\014\uffe8" +
    "\015\uffe8\016\uffe8\020\uffe8\022\uffe8\023\uffe8\024\uffe8\025" +
    "\uffe8\026\uffe8\027\uffe8\030\uffe8\031\uffe8\032\uffe8\033\uffe8" +
    "\034\uffe8\035\uffe8\036\uffe8\037\uffe8\040\uffe8\041\uffe8\042" +
    "\uffe8\056\uffe8\057\uffe8\060\uffe8\061\053\062\054\063\uffe8" +
    "\064\uffe8\065\uffe8\066\uffe8\067\uffe8\070\uffe8\071\uffe8\072" +
    "\uffe8\074\uffe8\001\002\000\126\002\uffe7\003\uffe7\004\uffe7" +
    "\006\uffe7\007\uffe7\011\uffe7\013\uffe7\014\uffe7\015\uffe7\016" +
    "\uffe7\020\uffe7\022\uffe7\023\uffe7\024\uffe7\025\uffe7\026\uffe7" +
    "\027\uffe7\030\uffe7\031\uffe7\032\uffe7\033\uffe7\034\uffe7\035" +
    "\uffe7\036\uffe7\037\uffe7\040\uffe7\041\uffe7\042\uffe7\056\uffe7" +
    "\057\uffe7\060\uffe7\061\053\062\054\063\uffe7\064\uffe7\065" +
    "\uffe7\066\uffe7\067\uffe7\070\uffe7\071\uffe7\072\uffe7\074\uffe7" +
    "\001\002\000\010\056\064\057\060\060\057\001\002\000" +
    "\126\002\uffdf\003\uffdf\004\uffdf\006\uffdf\007\uffdf\011\uffdf" +
    "\013\uffdf\014\uffdf\015\uffdf\016\uffdf\020\uffdf\022\uffdf\023" +
    "\uffdf\024\uffdf\025\uffdf\026\uffdf\027\uffdf\030\uffdf\031\uffdf" +
    "\032\uffdf\033\uffdf\034\uffdf\035\uffdf\036\uffdf\037\uffdf\040" +
    "\uffdf\041\uffdf\042\uffdf\056\uffdf\057\uffdf\060\uffdf\061\uffdf" +
    "\062\uffdf\063\uffdf\064\uffdf\065\uffdf\066\uffdf\067\uffdf\070" +
    "\uffdf\071\uffdf\072\uffdf\074\uffdf\001\002\000\012\055\046" +
    "\074\045\077\052\100\047\001\002\000\052\002\uffda\003" +
    "\uffda\023\uffda\024\uffda\025\uffda\026\uffda\027\uffda\030\uffda" +
    "\031\uffda\032\uffda\033\uffda\034\uffda\035\uffda\036\uffda\037" +
    "\uffda\040\uffda\041\uffda\042\uffda\057\060\060\057\001\002" +
    "\000\014\055\046\074\045\076\070\077\052\100\047\001" +
    "\002\000\004\020\uffca\001\002\000\004\020\100\001\002" +
    "\000\010\022\074\057\060\060\057\001\002\000\004\020" +
    "\uffc9\001\002\000\012\055\046\074\045\077\052\100\047" +
    "\001\002\000\010\022\076\057\060\060\057\001\002\000" +
    "\012\055\046\074\045\077\052\100\047\001\002\000\010" +
    "\020\uffc8\057\060\060\057\001\002\000\012\055\046\074" +
    "\045\077\052\100\047\001\002\000\052\002\uffd8\003\uffd8" +
    "\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8\031" +
    "\uffd8\032\uffd8\033\uffd8\034\uffd8\035\uffd8\036\uffd8\037\uffd8" +
    "\040\uffd8\041\uffd8\042\uffd8\057\060\060\057\001\002\000" +
    "\014\055\046\074\045\076\070\077\052\100\047\001\002" +
    "\000\004\020\104\001\002\000\012\055\046\074\045\077" +
    "\052\100\047\001\002\000\052\002\uffd4\003\uffd4\023\uffd4" +
    "\024\uffd4\025\uffd4\026\uffd4\027\uffd4\030\uffd4\031\uffd4\032" +
    "\uffd4\033\uffd4\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4" +
    "\041\uffd4\042\uffd4\057\060\060\057\001\002\000\016\043" +
    "\041\044\040\045\037\046\034\047\042\050\036\001\002" +
    "\000\004\020\110\001\002\000\012\055\046\074\045\077" +
    "\052\100\047\001\002\000\052\002\uffd2\003\uffd2\023\uffd2" +
    "\024\uffd2\025\uffd2\026\uffd2\027\uffd2\030\uffd2\031\uffd2\032" +
    "\uffd2\033\uffd2\034\uffd2\035\uffd2\036\uffd2\037\uffd2\040\uffd2" +
    "\041\uffd2\042\uffd2\057\060\060\057\001\002\000\012\051" +
    "\115\052\116\053\114\054\117\001\002\000\004\020\120" +
    "\001\002\000\004\020\uffbf\001\002\000\004\020\uffc1\001" +
    "\002\000\004\020\uffc0\001\002\000\004\020\uffbe\001\002" +
    "\000\012\055\046\074\045\077\052\100\047\001\002\000" +
    "\052\002\uffd1\003\uffd1\023\uffd1\024\uffd1\025\uffd1\026\uffd1" +
    "\027\uffd1\030\uffd1\031\uffd1\032\uffd1\033\uffd1\034\uffd1\035" +
    "\uffd1\036\uffd1\037\uffd1\040\uffd1\041\uffd1\042\uffd1\057\060" +
    "\060\057\001\002\000\014\055\046\074\045\076\070\077" +
    "\052\100\047\001\002\000\004\020\124\001\002\000\012" +
    "\055\046\074\045\077\052\100\047\001\002\000\052\002" +
    "\uffd9\003\uffd9\023\uffd9\024\uffd9\025\uffd9\026\uffd9\027\uffd9" +
    "\030\uffd9\031\uffd9\032\uffd9\033\uffd9\034\uffd9\035\uffd9\036" +
    "\uffd9\037\uffd9\040\uffd9\041\uffd9\042\uffd9\057\060\060\057" +
    "\001\002\000\012\055\046\074\045\077\052\100\047\001" +
    "\002\000\010\020\130\057\060\060\057\001\002\000\012" +
    "\055\046\074\045\077\052\100\047\001\002\000\052\002" +
    "\uffcb\003\uffcb\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb" +
    "\030\uffcb\031\uffcb\032\uffcb\033\uffcb\034\uffcb\035\uffcb\036" +
    "\uffcb\037\uffcb\040\uffcb\041\uffcb\042\uffcb\057\060\060\057" +
    "\001\002\000\016\043\041\044\040\045\037\046\034\047" +
    "\042\050\036\001\002\000\004\020\134\001\002\000\012" +
    "\055\046\074\045\077\052\100\047\001\002\000\052\002" +
    "\uffd7\003\uffd7\023\uffd7\024\uffd7\025\uffd7\026\uffd7\027\uffd7" +
    "\030\uffd7\031\uffd7\032\uffd7\033\uffd7\034\uffd7\035\uffd7\036" +
    "\uffd7\037\uffd7\040\uffd7\041\uffd7\042\uffd7\057\060\060\057" +
    "\001\002\000\014\055\046\074\045\076\070\077\052\100" +
    "\047\001\002\000\004\020\140\001\002\000\012\055\046" +
    "\074\045\077\052\100\047\001\002\000\052\002\uffd3\003" +
    "\uffd3\023\uffd3\024\uffd3\025\uffd3\026\uffd3\027\uffd3\030\uffd3" +
    "\031\uffd3\032\uffd3\033\uffd3\034\uffd3\035\uffd3\036\uffd3\037" +
    "\uffd3\040\uffd3\041\uffd3\042\uffd3\057\060\060\057\001\002" +
    "\000\014\055\046\074\045\076\070\077\052\100\047\001" +
    "\002\000\004\020\144\001\002\000\012\055\046\074\045" +
    "\077\052\100\047\001\002\000\052\002\uffce\003\uffce\023" +
    "\uffce\024\uffce\025\uffce\026\uffce\027\uffce\030\uffce\031\uffce" +
    "\032\uffce\033\uffce\034\uffce\035\uffce\036\uffce\037\uffce\040" +
    "\uffce\041\uffce\042\uffce\057\060\060\057\001\002\000\012" +
    "\055\046\074\045\077\052\100\047\001\002\000\010\020" +
    "\150\057\060\060\057\001\002\000\012\055\046\074\045" +
    "\077\052\100\047\001\002\000\052\002\uffd0\003\uffd0\023" +
    "\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031\uffd0" +
    "\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0\040" +
    "\uffd0\041\uffd0\042\uffd0\057\060\060\057\001\002\000\046" +
    "\002\uffdb\003\uffdb\023\uffdb\024\uffdb\025\uffdb\026\uffdb\027" +
    "\uffdb\030\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb\035\uffdb" +
    "\036\uffdb\037\uffdb\040\uffdb\041\uffdb\042\uffdb\001\002\000" +
    "\046\002\uffdd\003\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd" +
    "\027\uffdd\030\uffdd\031\uffdd\032\uffdd\033\uffdd\034\uffdd\035" +
    "\uffdd\036\uffdd\037\uffdd\040\uffdd\041\uffdd\042\uffdd\001\002" +
    "\000\012\051\115\052\116\053\114\054\117\001\002\000" +
    "\004\020\156\001\002\000\012\055\046\074\045\077\052" +
    "\100\047\001\002\000\052\002\uffcc\003\uffcc\023\uffcc\024" +
    "\uffcc\025\uffcc\026\uffcc\027\uffcc\030\uffcc\031\uffcc\032\uffcc" +
    "\033\uffcc\034\uffcc\035\uffcc\036\uffcc\037\uffcc\040\uffcc\041" +
    "\uffcc\042\uffcc\057\060\060\057\001\002\000\012\051\115" +
    "\052\116\053\114\054\117\001\002\000\004\020\162\001" +
    "\002\000\012\055\046\074\045\077\052\100\047\001\002" +
    "\000\052\002\uffd6\003\uffd6\023\uffd6\024\uffd6\025\uffd6\026" +
    "\uffd6\027\uffd6\030\uffd6\031\uffd6\032\uffd6\033\uffd6\034\uffd6" +
    "\035\uffd6\036\uffd6\037\uffd6\040\uffd6\041\uffd6\042\uffd6\057" +
    "\060\060\057\001\002\000\014\055\046\074\045\076\070" +
    "\077\052\100\047\001\002\000\004\020\166\001\002\000" +
    "\012\055\046\074\045\077\052\100\047\001\002\000\052" +
    "\002\uffcf\003\uffcf\023\uffcf\024\uffcf\025\uffcf\026\uffcf\027" +
    "\uffcf\030\uffcf\031\uffcf\032\uffcf\033\uffcf\034\uffcf\035\uffcf" +
    "\036\uffcf\037\uffcf\040\uffcf\041\uffcf\042\uffcf\057\060\060" +
    "\057\001\002\000\012\055\046\074\045\077\052\100\047" +
    "\001\002\000\010\020\172\057\060\060\057\001\002\000" +
    "\012\055\046\074\045\077\052\100\047\001\002\000\052" +
    "\002\uffd5\003\uffd5\023\uffd5\024\uffd5\025\uffd5\026\uffd5\027" +
    "\uffd5\030\uffd5\031\uffd5\032\uffd5\033\uffd5\034\uffd5\035\uffd5" +
    "\036\uffd5\037\uffd5\040\uffd5\041\uffd5\042\uffd5\057\060\060" +
    "\057\001\002\000\026\003\ufffc\004\ufffc\006\ufffc\007\ufffc" +
    "\011\ufffc\013\ufffc\014\ufffc\015\ufffc\016\ufffc\074\ufffc\001" +
    "\002\000\006\074\263\075\262\001\002\000\004\074\257" +
    "\001\002\000\004\074\256\001\002\000\016\004\176\007" +
    "\203\011\201\013\175\014\177\074\204\001\002\000\004" +
    "\055\247\001\002\000\022\003\225\004\176\006\246\007" +
    "\203\011\201\013\175\014\177\074\204\001\002\000\004" +
    "\055\207\001\002\000\004\021\205\001\002\000\012\055" +
    "\046\074\045\077\052\100\047\001\002\000\032\003\ufff8" +
    "\004\ufff8\006\ufff8\007\ufff8\011\ufff8\013\ufff8\014\ufff8\015" +
    "\ufff8\016\ufff8\057\060\060\057\074\ufff8\001\002\000\014" +
    "\055\211\073\213\074\045\077\052\100\047\001\002\000" +
    "\022\057\060\060\057\063\232\064\235\065\236\066\233" +
    "\067\234\070\237\001\002\000\014\055\211\073\213\074" +
    "\045\077\052\100\047\001\002\000\010\056\221\071\215" +
    "\072\216\001\002\000\014\055\211\073\213\074\045\077" +
    "\052\100\047\001\002\000\010\056\uffea\071\uffea\072\uffea" +
    "\001\002\000\014\055\211\073\213\074\045\077\052\100" +
    "\047\001\002\000\014\055\211\073\213\074\045\077\052" +
    "\100\047\001\002\000\010\056\uffeb\071\215\072\uffeb\001" +
    "\002\000\010\056\uffec\071\uffec\072\uffec\001\002\000\004" +
    "\010\222\001\002\000\020\003\200\004\176\007\203\011" +
    "\201\013\175\014\177\074\204\001\002\000\022\003\225" +
    "\004\176\007\203\011\201\013\175\014\177\015\226\074" +
    "\204\001\002\000\026\003\ufffd\004\ufffd\006\ufffd\007\ufffd" +
    "\011\ufffd\013\ufffd\014\ufffd\015\ufffd\016\ufffd\074\ufffd\001" +
    "\002\000\026\003\ufffa\004\ufffa\006\ufffa\007\ufffa\011\ufffa" +
    "\013\ufffa\014\ufffa\015\ufffa\016\ufffa\074\ufffa\001\002\000" +
    "\026\003\ufff4\004\ufff4\006\ufff4\007\ufff4\011\ufff4\013\ufff4" +
    "\014\ufff4\015\ufff4\016\ufff4\074\ufff4\001\002\000\024\056" +
    "\064\057\060\060\057\063\232\064\235\065\236\066\233" +
    "\067\234\070\237\001\002\000\010\056\231\071\215\072" +
    "\216\001\002\000\010\056\uffe9\071\uffe9\072\uffe9\001\002" +
    "\000\012\055\046\074\045\077\052\100\047\001\002\000" +
    "\012\055\046\074\045\077\052\100\047\001\002\000\012" +
    "\055\046\074\045\077\052\100\047\001\002\000\012\055" +
    "\046\074\045\077\052\100\047\001\002\000\012\055\046" +
    "\074\045\077\052\100\047\001\002\000\012\055\046\074" +
    "\045\077\052\100\047\001\002\000\014\056\uffee\057\060" +
    "\060\057\071\uffee\072\uffee\001\002\000\014\056\uffef\057" +
    "\060\060\057\071\uffef\072\uffef\001\002\000\014\056\ufff1" +
    "\057\060\060\057\071\ufff1\072\ufff1\001\002\000\014\056" +
    "\uffed\057\060\060\057\071\uffed\072\uffed\001\002\000\014" +
    "\056\ufff0\057\060\060\057\071\ufff0\072\ufff0\001\002\000" +
    "\014\056\ufff2\057\060\060\057\071\ufff2\072\ufff2\001\002" +
    "\000\006\002\ufffe\017\ufffe\001\002\000\014\055\211\073" +
    "\213\074\045\077\052\100\047\001\002\000\010\056\251" +
    "\071\215\072\216\001\002\000\004\012\252\001\002\000" +
    "\020\003\200\004\176\007\203\011\201\013\175\014\177" +
    "\074\204\001\002\000\022\003\225\004\176\007\203\011" +
    "\201\013\175\014\177\016\254\074\204\001\002\000\026" +
    "\003\ufff3\004\ufff3\006\ufff3\007\ufff3\011\ufff3\013\ufff3\014" +
    "\ufff3\015\ufff3\016\ufff3\074\ufff3\001\002\000\026\003\ufffb" +
    "\004\ufffb\006\ufffb\007\ufffb\011\ufffb\013\ufffb\014\ufffb\015" +
    "\ufffb\016\ufffb\074\ufffb\001\002\000\026\003\ufff5\004\ufff5" +
    "\006\ufff5\007\ufff5\011\ufff5\013\ufff5\014\ufff5\015\ufff5\016" +
    "\ufff5\074\ufff5\001\002\000\004\021\260\001\002\000\012" +
    "\055\046\074\045\077\052\100\047\001\002\000\032\003" +
    "\ufff9\004\ufff9\006\ufff9\007\ufff9\011\ufff9\013\ufff9\014\ufff9" +
    "\015\ufff9\016\ufff9\057\060\060\057\074\ufff9\001\002\000" +
    "\026\003\ufff7\004\ufff7\006\ufff7\007\ufff7\011\ufff7\013\ufff7" +
    "\014\ufff7\015\ufff7\016\ufff7\074\ufff7\001\002\000\026\003" +
    "\ufff6\004\ufff6\006\ufff6\007\ufff6\011\ufff6\013\ufff6\014\ufff6" +
    "\015\ufff6\016\ufff6\074\ufff6\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\262\000\006\002\003\003\005\001\001\000\002\001" +
    "\001\000\006\004\201\005\173\001\001\000\002\001\001" +
    "\000\010\012\020\013\013\014\030\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\152\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\007\047\010\050\011\043" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\062\010\050\011\043\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\055\001\001\000\004\011\054\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\010\061\011\043\001\001\000" +
    "\006\010\060\011\043\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\065\010\050\011\043\001\001\000\002\001\001\000\014" +
    "\007\071\010\050\011\043\015\070\016\072\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\007\074\010\050\011\043\001\001\000" +
    "\002\001\001\000\010\007\076\010\050\011\043\001\001" +
    "\000\002\001\001\000\010\007\100\010\050\011\043\001" +
    "\001\000\002\001\001\000\014\007\071\010\050\011\043" +
    "\015\102\016\072\001\001\000\002\001\001\000\010\007" +
    "\104\010\050\011\043\001\001\000\002\001\001\000\004" +
    "\017\106\001\001\000\002\001\001\000\010\007\110\010" +
    "\050\011\043\001\001\000\002\001\001\000\004\020\112" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\007\120" +
    "\010\050\011\043\001\001\000\002\001\001\000\014\007" +
    "\071\010\050\011\043\015\122\016\072\001\001\000\002" +
    "\001\001\000\010\007\124\010\050\011\043\001\001\000" +
    "\002\001\001\000\010\007\126\010\050\011\043\001\001" +
    "\000\002\001\001\000\010\007\130\010\050\011\043\001" +
    "\001\000\002\001\001\000\004\017\132\001\001\000\002" +
    "\001\001\000\010\007\134\010\050\011\043\001\001\000" +
    "\002\001\001\000\014\007\071\010\050\011\043\015\136" +
    "\016\072\001\001\000\002\001\001\000\010\007\140\010" +
    "\050\011\043\001\001\000\002\001\001\000\014\007\071" +
    "\010\050\011\043\015\142\016\072\001\001\000\002\001" +
    "\001\000\010\007\144\010\050\011\043\001\001\000\002" +
    "\001\001\000\010\007\146\010\050\011\043\001\001\000" +
    "\002\001\001\000\010\007\150\010\050\011\043\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\154\001\001\000\002\001\001\000\010\007\156" +
    "\010\050\011\043\001\001\000\002\001\001\000\004\020" +
    "\160\001\001\000\002\001\001\000\010\007\162\010\050" +
    "\011\043\001\001\000\002\001\001\000\014\007\071\010" +
    "\050\011\043\015\164\016\072\001\001\000\002\001\001" +
    "\000\010\007\166\010\050\011\043\001\001\000\002\001" +
    "\001\000\010\007\170\010\050\011\043\001\001\000\002" +
    "\001\001\000\010\007\172\010\050\011\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\254\001\001\000" +
    "\002\001\001\000\004\005\223\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\007\205\010\050\011\043\001" +
    "\001\000\002\001\001\000\012\006\211\007\207\010\050" +
    "\011\043\001\001\000\002\001\001\000\012\006\227\007" +
    "\226\010\050\011\043\001\001\000\002\001\001\000\012" +
    "\006\213\007\207\010\050\011\043\001\001\000\002\001" +
    "\001\000\012\006\217\007\207\010\050\011\043\001\001" +
    "\000\012\006\216\007\207\010\050\011\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\004\222\005\173\001\001\000\004\005\223\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\244\010\050\011\043\001\001\000\010\007\243\010\050" +
    "\011\043\001\001\000\010\007\242\010\050\011\043\001" +
    "\001\000\010\007\241\010\050\011\043\001\001\000\010" +
    "\007\240\010\050\011\043\001\001\000\010\007\237\010" +
    "\050\011\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\006\247\007\207" +
    "\010\050\011\043\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\252\005\173\001\001\000\004\005\223" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\007\260\010\050\011\043" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private List<String> syntaxErrors = new ArrayList<>();

    public List<String> getSyntaxErrors(){
        return this.syntaxErrors;
    }

    public void syntax_error(Symbol cur_token) {
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : "EOF";
        int linea = cur_token.left;
        int columna = cur_token.right;
        syntaxErrors.add("Error sintáctico en línea " + linea + ", columna " + columna + ". Token inesperado: " + lexema);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= bloque_codigo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= bloque_codigo SEPARADOR bloque_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // bloque_codigo ::= INICIO lista_sentencias FIN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_codigo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_sentencias ::= error sentencia 
            {
              Object RESULT =null;
		 /* Al encontrar un error, intenta seguir con la siguiente sentencia */ 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // lista_sentencias ::= lista_sentencias error 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= VAR IDENTIFICADOR ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= IDENTIFICADOR ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= MOSTRAR TEXTO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= MOSTRAR IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= LEER IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= SI PARENTESIS_IZQUIERDO condicion PARENTESIS_DERECHO ENTONCES lista_sentencias FINSI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= MIENTRAS PARENTESIS_IZQUIERDO condicion PARENTESIS_DERECHO HACER lista_sentencias FINMIENTRAS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // condicion ::= expresion IGUALDAD expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // condicion ::= expresion DIFERENCIA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // condicion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // condicion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // condicion ::= expresion MENOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // condicion ::= expresion MAYOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // condicion ::= condicion AND condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // condicion ::= condicion OR condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // condicion ::= NOT condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // condicion ::= PARENTESIS_IZQUIERDO condicion PARENTESIS_DERECHO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= expresion SUMA termino 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= expresion RESTA termino 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion ::= termino 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // termino ::= termino MULTIPLICACION factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // termino ::= termino DIVISION factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // termino ::= factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // factor ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // factor ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // factor ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // factor ::= PARENTESIS_IZQUIERDO expresion PARENTESIS_DERECHO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // bloque_config ::= lista_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_config",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // lista_config ::= lista_config instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // lista_config ::= instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_config ::= lista_config error 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // instruccion_config ::= DEFAULT ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // instruccion_config ::= COLOR_TEXTO_SI ASIGNACION color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instruccion_config ::= COLOR_SI ASIGNACION color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instruccion_config ::= FIGURA_SI ASIGNACION figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // instruccion_config ::= LETRA_SI ASIGNACION letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion_config ::= LETRA_SIZE_SI ASIGNACION expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_config ::= COLOR_TEXTO_MIENTRAS ASIGNACION color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // instruccion_config ::= COLOR_MIENTRAS ASIGNACION color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // instruccion_config ::= FIGURA_MIENTRAS ASIGNACION figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // instruccion_config ::= LETRA_MIENTRAS ASIGNACION letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // instruccion_config ::= LETRA_SIZE_MIENTRAS ASIGNACION expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // instruccion_config ::= COLOR_TEXTO_BLOQUE ASIGNACION color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // instruccion_config ::= COLOR_BLOQUE ASIGNACION color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // instruccion_config ::= FIGURA_BLOQUE ASIGNACION figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // instruccion_config ::= LETRA_BLOQUE ASIGNACION letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // instruccion_config ::= LETRA_SIZE_BLOQUE ASIGNACION expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // color ::= COLOR_HEX 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // color ::= rgb 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // rgb ::= expresion COMA expresion COMA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rgb",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // figura ::= ELIPSE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // figura ::= CIRCULO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // figura ::= PARALELOGRAMO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // figura ::= RECTANGULO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // figura ::= ROMBO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // figura ::= RECTANGULO_REDONDEADO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // letra ::= ARIAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // letra ::= TIME_NEW_ROMAN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // letra ::= COMIC_SANS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // letra ::= VERDANA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
