
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.compiapp.logic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_DERECHO = 44;
  public static final int DIFERENCIA = 50;
  public static final int PARENTESIS_IZQUIERDO = 43;
  public static final int COLOR_TEXTO_BLOQUE = 28;
  public static final int LETRA_SIZE_MIENTRAS = 27;
  public static final int ENTERO = 61;
  public static final int SI = 5;
  public static final int MOSTRAR = 9;
  public static final int FIGURA_BLOQUE = 30;
  public static final int RESTA = 46;
  public static final int LETRA_MIENTRAS = 26;
  public static final int ENTONCES = 6;
  public static final int RECTANGULO_REDONDEADO = 38;
  public static final int SEPARADOR = 13;
  public static final int FIN = 4;
  public static final int IDENTIFICADOR = 58;
  public static final int NOT = 57;
  public static final int AND = 55;
  public static final int FINMIENTRAS = 12;
  public static final int OR = 56;
  public static final int IGUALDAD = 49;
  public static final int MIENTRAS = 7;
  public static final int LETRA_SIZE_BLOQUE = 32;
  public static final int ARIAL = 39;
  public static final int SUMA = 45;
  public static final int CIRCULO = 34;
  public static final int COLOR_HEX = 60;
  public static final int DECIMAL = 62;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int COLOR_BLOQUE = 29;
  public static final int COMIC_SANS = 41;
  public static final int PIPE = 14;
  public static final int MENOR = 52;
  public static final int COLOR_MIENTRAS = 24;
  public static final int COLOR_TEXTO_MIENTRAS = 23;
  public static final int VERDANA = 42;
  public static final int LETRA_BLOQUE = 31;
  public static final int ASIGNACION = 15;
  public static final int MAYOR = 51;
  public static final int ELIPSE = 33;
  public static final int ROMBO = 37;
  public static final int TIME_NEW_ROMAN = 40;
  public static final int RECTANGULO = 36;
  public static final int FIGURA_MIENTRAS = 25;
  public static final int MAYOR_IGUAL = 53;
  public static final int DEFAULT = 17;
  public static final int LEER = 10;
  public static final int HACER = 8;
  public static final int COLOR_SI = 19;
  public static final int LETRA_SI = 21;
  public static final int PARALELOGRAMO = 35;
  public static final int INICIO = 3;
  public static final int TEXTO = 59;
  public static final int MENOR_IGUAL = 54;
  public static final int DIVISION = 48;
  public static final int FINSI = 11;
  public static final int COLOR_TEXTO_SI = 18;
  public static final int FIGURA_SI = 20;
  public static final int VAR = 2;
  public static final int MULTIPLICACION = 47;
  public static final int LETRA_SIZE_SI = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "INICIO",
  "FIN",
  "SI",
  "ENTONCES",
  "MIENTRAS",
  "HACER",
  "MOSTRAR",
  "LEER",
  "FINSI",
  "FINMIENTRAS",
  "SEPARADOR",
  "PIPE",
  "ASIGNACION",
  "COMA",
  "DEFAULT",
  "COLOR_TEXTO_SI",
  "COLOR_SI",
  "FIGURA_SI",
  "LETRA_SI",
  "LETRA_SIZE_SI",
  "COLOR_TEXTO_MIENTRAS",
  "COLOR_MIENTRAS",
  "FIGURA_MIENTRAS",
  "LETRA_MIENTRAS",
  "LETRA_SIZE_MIENTRAS",
  "COLOR_TEXTO_BLOQUE",
  "COLOR_BLOQUE",
  "FIGURA_BLOQUE",
  "LETRA_BLOQUE",
  "LETRA_SIZE_BLOQUE",
  "ELIPSE",
  "CIRCULO",
  "PARALELOGRAMO",
  "RECTANGULO",
  "ROMBO",
  "RECTANGULO_REDONDEADO",
  "ARIAL",
  "TIME_NEW_ROMAN",
  "COMIC_SANS",
  "VERDANA",
  "PARENTESIS_IZQUIERDO",
  "PARENTESIS_DERECHO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "IGUALDAD",
  "DIFERENCIA",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "IDENTIFICADOR",
  "TEXTO",
  "COLOR_HEX",
  "ENTERO",
  "DECIMAL"
  };
}

